<script setup lang="ts">
/**
 * UpdateModal — marketing-first update prompt (v2.0.1).
 *
 * The Tauri updater's manifest body is auto-generated by the release CI
 * (download table + raw "see the changelog" link). Rendering it raw made
 * the modal look like a CI artifact dump. We deliberately ignore the body
 * here and surface a curated, version-agnostic frame instead:
 *
 *   - Hero: sparkle + version
 *   - Tagline: localized "discover what's new" line
 *   - Link: "See the full changelog" → website (where Laurent maintains
 *     human-friendly release notes)
 *   - CTA: install / open release page (beta)
 *
 * The body is still kept on `UpdateInfo` for future iterations (e.g. when
 * we publish hand-written marketing copy in the manifest), but until that
 * pipeline exists, surfacing the CI text was a net negative.
 */
import { ref, computed } from "vue";
import BaseModal from "./BaseModal.vue";
import AiSparkle from "./AiSparkle.vue";
import type { UpdateInfo } from "../utils/backend";
import { useI18n } from "../composables/useI18n";

const { t } = useI18n();

const props = defineProps<{
  update: UpdateInfo;
}>();

const emit = defineEmits<{
  close: [];
  install: [];
}>();

const installing = ref(false);
const progress = ref(0); // 0–1

/** Expose progress setter so App.vue can relay onProgress callbacks */
function setProgress(fraction: number) {
  progress.value = fraction;
}
defineExpose({ setProgress });

const progressPct = computed(() => Math.round(progress.value * 100));

/** Manual install path = beta channel — no in-app download/replace. */
const isManual = computed(() => props.update.installMethod === "manual");

const ctaLabel = computed(() => {
  if (installing.value) return t("update.installing");
  if (isManual.value) return t("update.openReleasePage");
  return t("update.installAndRestart");
});

/** Anchor the changelog link to the version's heading on the website
 *  (VitePress slugifies "v2.0.1" → "v2-0-1"). Falls back to the page top
 *  when the anchor doesn't match (older releases without a heading). */
const CHANGELOG_BASE = "https://gitwand.devlint.fr/changelog";
const changelogUrl = computed(() => {
  const slug = `v${props.update.version.replace(/\./g, "-")}`;
  return `${CHANGELOG_BASE}#${slug}`;
});

function onInstall() {
  // Manual path closes the modal immediately after opening the browser
  // (App.vue handles the window.open + state reset). Don't lock the UI
  // into the "installing" state since there's no in-app progress to show.
  if (!isManual.value) installing.value = true;
  emit("install");
}
</script>

<template>
  <BaseModal
    :title="t('update.title', update.version)"
    size="md"
    role="dialog"
    :closable="!installing"
    @close="emit('close')"
  >
    <!-- Title icon: download-into-tray glyph for "new version ready" -->
    <template #title-icon>
      <span class="um-title-icon" aria-hidden="true">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none">
          <path
            d="M12 3v12m0 0l-4-4m4 4l4-4M5 19h14"
            stroke="currentColor"
            stroke-width="1.7"
            stroke-linecap="round"
            stroke-linejoin="round"
          />
        </svg>
      </span>
    </template>

    <!-- Hero: sparkle + version + badge (both in accent violet) -->
    <div class="um-hero">
      <span class="um-sparkle" aria-hidden="true">
        <AiSparkle :size="24" />
      </span>
      <div class="um-hero-text">
        <span class="um-badge">{{ isManual ? t('update.betaBadge') : t('update.newBadge') }}</span>
        <span class="um-version">v{{ update.version }}</span>
      </div>
    </div>

    <!-- Marketing tagline — generic, works for any release without depending
         on the manifest body being well-written. -->
    <p class="um-tagline">{{ t('update.tagline') }}</p>

    <!-- Beta channel hint — explains why the button opens a browser -->
    <p v-if="isManual" class="um-manual-hint">
      {{ t('update.manualHint') }}
    </p>

    <!-- Link to the website's full changelog. Opens in the user's browser. -->
    <a
      class="um-changelog-link"
      :href="changelogUrl"
      target="_blank"
      rel="noopener noreferrer"
    >
      {{ t('update.viewChangelog') }}
      <svg width="12" height="12" viewBox="0 0 16 16" fill="none" aria-hidden="true">
        <path d="M6 4h6v6M12 4l-8 8" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    </a>

    <!-- Download progress bar (auto channel only) -->
    <div v-if="installing" class="um-progress">
      <div class="um-progress__bar" :style="{ width: progressPct + '%' }" />
      <span class="um-progress__label">
        {{ progress > 0 ? `${progressPct}%` : t('update.downloading') }}
      </span>
    </div>

    <!-- Footer -->
    <template #footer>
      <button
        class="bm-btn bm-btn--ghost"
        :disabled="installing"
        @click="emit('close')"
      >
        {{ t('update.later') }}
      </button>
      <button
        class="bm-btn bm-btn--primary"
        :disabled="installing"
        @click="onInstall"
      >
        <span v-if="installing" class="um-spinner" aria-hidden="true" />
        {{ ctaLabel }}
      </button>
    </template>
  </BaseModal>
</template>

<style scoped>
/* All colors come from the design-system tokens (--color-accent,
   --color-text, --color-bg-*, --color-border) — same vocabulary the rest
   of the modal family uses. The previous CSS in this file referenced
   undefined `--accent`, `--text-primary`, `--bg-tertiary` etc., which
   silently fell back to black on white in light mode. */

/* Hero — sparkle in an accent-soft tile next to the version block */
.um-hero {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: var(--space-4);
  margin-top: var(--space-3);
  margin-bottom: var(--space-6);
}

.um-sparkle {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 44px;
  height: 44px;
  border-radius: var(--radius-pill);
  background: var(--color-accent-soft);
  color: var(--color-accent);
  flex-shrink: 0;
}

.um-hero-text {
  display: flex;
  flex-direction: column;
  gap: 0;
  line-height: 1;
  min-width: 0;
}

.um-badge {
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--color-accent);
}

.um-version {
  font-size: 22px;
  font-weight: 700;
  /* Accent violet — matches the sparkle + badge so the hero reads as one
     unified "Nouvelle version v2.0.1" block instead of mixed colors. */
  color: var(--color-accent);
  letter-spacing: -0.01em;
}

/* Title-icon — soft-accent tile sized to match BaseModal's title row.
   Same vocabulary as BranchRenameModal / CloneModal so the chrome feels
   consistent across the modal family. */
.um-title-icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 36px;
  height: 36px;
  border-radius: var(--radius-pill);
  background: var(--color-accent-soft);
  color: var(--color-accent);
  flex-shrink: 0;
}

/* Tagline — large-but-light marketing line */
.um-tagline {
  margin: 0 0 var(--space-4) 0;
  font-size: 15px;
  line-height: 1.55;
  color: var(--color-text-muted);
}

/* Changelog link — text-ghost CTA */
.um-changelog-link {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  margin-bottom: var(--space-4);
  font-size: 13px;
  font-weight: 500;
  color: var(--color-accent);
  text-decoration: none;
  transition: color var(--transition-fast);
}

.um-changelog-link:hover {
  color: var(--color-accent-hover, var(--color-accent));
  text-decoration: underline;
}

.um-changelog-link svg {
  flex-shrink: 0;
}

/* Beta-channel hint kept from previous design */
.um-manual-hint {
  margin: 0 0 var(--space-4) 0;
  padding: var(--space-3) var(--space-4);
  background: var(--color-accent-soft);
  border: 1px solid var(--color-border);
  border-left: 3px solid var(--color-accent);
  border-radius: var(--radius-md);
  font-size: 12px;
  line-height: 1.55;
  color: var(--color-text-muted);
}

/* Progress bar */
.um-progress {
  position: relative;
  height: 6px;
  background: var(--color-bg-tertiary);
  border-radius: 99px;
  overflow: hidden;
  margin-bottom: var(--space-3);
}

.um-progress__bar {
  position: absolute;
  inset: 0 auto 0 0;
  background: var(--color-accent);
  border-radius: 99px;
  transition: width 0.2s ease;
  min-width: 4%;
}

.um-progress__label {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 10px;
  font-weight: 600;
  color: var(--color-text);
  /* shift below bar so text is readable */
  margin-top: 10px;
}

/* Spinner inside button */
.um-spinner {
  display: inline-block;
  width: 12px;
  height: 12px;
  border: 2px solid currentColor;
  border-top-color: transparent;
  border-radius: 50%;
  animation: um-spin 0.7s linear infinite;
  margin-right: var(--space-2);
  vertical-align: middle;
}

@keyframes um-spin {
  to { transform: rotate(360deg); }
}
</style>
