/**
 * Tests du resolver lockfile-yarn (yarn.lock) — GitWand
 *
 * Fixtures :
 *   F1 — bloc de package ajouté d'un seul côté
 *   F2 — même bloc, version différente → prefer theirs
 *   F3 — yarn.lock minimal
 *   F4 — deux packages différents ajoutés de chaque côté
 *   F5 — détection du nom `yarn.lock` → bon resolver utilisé
 */

import { describe, it, expect } from "vitest";
import { resolve } from "../../resolver.js";

// ─── base lockfile ─────────────────────────────────────────────────────────────

const baseLock = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

react@^18.0.0:
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz"
  integrity sha512-react

vue@^3.0.0:
  version "3.4.0"
  resolved "https://registry.yarnpkg.com/vue/-/vue-3.4.0.tgz"
  integrity sha512-vue
`;

// ─── F1 — bloc de package ajouté d'un seul côté ──────────────────────────────

describe("F1 — yarn.lock : bloc de package ajouté d'un seul côté (diff3)", () => {
  const oursLock = baseLock + `
axios@^1.0.0:
  version "1.6.0"
  resolved "https://registry.yarnpkg.com/axios/-/axios-1.6.0.tgz"
  integrity sha512-axios
`;

  const input = [
    `<<<<<<< ours`,
    ...oursLock.split("\n"),
    `||||||| base`,
    ...baseLock.split("\n"),
    `=======`,
    ...baseLock.split("\n"),
    `>>>>>>> theirs`,
  ].join("\n");

  it("auto-résout via le resolver lockfile-yarn", () => {
    const result = resolve(input, "yarn.lock");
    expect(result.stats.autoResolved).toBe(1);
  });

  it("le résultat contient le bloc de package ajouté", () => {
    const result = resolve(input, "yarn.lock");
    expect(result.mergedContent).toContain("axios@^1.0.0:");
    expect(result.mergedContent).toContain("react@^18.0.0:");
    expect(result.mergedContent).toContain("vue@^3.0.0:");
  });

  it("la raison mentionne [lockfile-yarn]", () => {
    const result = resolve(input, "yarn.lock");
    expect(result.resolutions[0].resolutionReason).toMatch(/\[lockfile-yarn\]/i);
  });
});

// ─── F2 — même bloc, version différente ───────────────────────────────────────

describe("F2 — yarn.lock : même bloc, version différente → prefer theirs (diff3)", () => {
  const oursLock = baseLock.replace('"18.2.0"', '"18.3.0"').replace("sha512-react", "sha512-react-ours");
  const theirsLock = baseLock.replace('"18.2.0"', '"18.3.1"').replace("sha512-react", "sha512-react-theirs");

  const input = [
    `<<<<<<< ours`,
    ...oursLock.split("\n"),
    `||||||| base`,
    ...baseLock.split("\n"),
    `=======`,
    ...theirsLock.split("\n"),
    `>>>>>>> theirs`,
  ].join("\n");

  it("ne lève pas d'exception", () => {
    expect(() => resolve(input, "yarn.lock")).not.toThrow();
  });

  it("la raison mentionne [lockfile-yarn]", () => {
    const result = resolve(input, "yarn.lock");
    expect(result.resolutions[0].resolutionReason).toMatch(/\[lockfile-yarn\]/i);
  });
});

// ─── F3 — yarn.lock minimal ───────────────────────────────────────────────────

describe("F3 — yarn.lock minimal : ne plante pas", () => {
  const minimal = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n`;

  const input = [
    `<<<<<<< ours`,
    ...minimal.split("\n"),
    `||||||| base`,
    ...minimal.split("\n"),
    `=======`,
    ...minimal.split("\n"),
    `>>>>>>> theirs`,
  ].join("\n");

  it("ne lève pas d'exception", () => {
    expect(() => resolve(input, "yarn.lock")).not.toThrow();
  });

  it("produit un résultat avec au moins un hunk", () => {
    const result = resolve(input, "yarn.lock");
    expect(result.hunks.length).toBeGreaterThanOrEqual(1);
  });
});

// ─── F4 — deux packages différents ajoutés de chaque côté ────────────────────

describe("F4 — yarn.lock : packages différents ajoutés de chaque côté (diff3)", () => {
  const oursLock = baseLock + `
lodash@^4.0.0:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-lodash
`;

  const theirsLock = baseLock + `
date-fns@^3.0.0:
  version "3.0.0"
  resolved "https://registry.yarnpkg.com/date-fns/-/date-fns-3.0.0.tgz"
  integrity sha512-datefns
`;

  const input = [
    `<<<<<<< ours`,
    ...oursLock.split("\n"),
    `||||||| base`,
    ...baseLock.split("\n"),
    `=======`,
    ...theirsLock.split("\n"),
    `>>>>>>> theirs`,
  ].join("\n");

  it("auto-résout avec les deux packages", () => {
    const result = resolve(input, "yarn.lock");
    expect(result.stats.autoResolved).toBe(1);
  });

  it("le résultat contient les deux packages ajoutés", () => {
    const result = resolve(input, "yarn.lock");
    expect(result.mergedContent).toContain("lodash@^4.0.0:");
    expect(result.mergedContent).toContain("date-fns@^3.0.0:");
    expect(result.mergedContent).toContain("react@^18.0.0:");
    expect(result.mergedContent).toContain("vue@^3.0.0:");
  });

  it("la raison mentionne [lockfile-yarn]", () => {
    const result = resolve(input, "yarn.lock");
    expect(result.resolutions[0].resolutionReason).toMatch(/\[lockfile-yarn\]/i);
  });
});

// ─── F5 — détection du nom de fichier ────────────────────────────────────────

describe("F5 — yarn.lock : détection du nom de fichier", () => {
  const oursLock = baseLock + `
zod@^3.0.0:
  version "3.22.0"
  resolved "https://registry.yarnpkg.com/zod/-/zod-3.22.0.tgz"
  integrity sha512-zod
`;

  const input = [
    `<<<<<<< ours`,
    ...oursLock.split("\n"),
    `||||||| base`,
    ...baseLock.split("\n"),
    `=======`,
    ...baseLock.split("\n"),
    `>>>>>>> theirs`,
  ].join("\n");

  it("le nom yarn.lock active le bon resolver", () => {
    const result = resolve(input, "yarn.lock");
    expect(result.resolutions[0].resolutionReason).toMatch(/\[lockfile-yarn\]/i);
  });

  it("le nom dans un sous-dossier est aussi détecté", () => {
    const result = resolve(input, "apps/desktop/yarn.lock");
    expect(result.resolutions[0].resolutionReason).toMatch(/\[lockfile-yarn\]/i);
  });
});
