import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Configuration","description":"","frontmatter":{},"headers":[],"relativePath":"reference/config.md","filePath":"reference/config.md"}');
const _sfc_main = { name: "reference/config.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="configuration" tabindex="-1">Configuration <a class="header-anchor" href="#configuration" aria-label="Permalink to &quot;Configuration&quot;">​</a></h1><p>GitWand is configured via a <code>.gitwandrc</code> file at the root of your repository, or via a <code>&quot;gitwand&quot;</code> key in <code>package.json</code>.</p><h2 id="file-format" tabindex="-1">File Format <a class="header-anchor" href="#file-format" aria-label="Permalink to &quot;File Format&quot;">​</a></h2><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;policy&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;prefer-safety&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;patterns&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    &quot;*.lock&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;prefer-theirs&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    &quot;package.json&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;prefer-theirs&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    &quot;src/**/*.ts&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;prefer-ours&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><h2 id="policies" tabindex="-1">Policies <a class="header-anchor" href="#policies" aria-label="Permalink to &quot;Policies&quot;">​</a></h2><p>A policy controls how aggressively GitWand auto-resolves conflicts.</p><table tabindex="0"><thead><tr><th>Policy</th><th>Behavior</th><th>Min Confidence</th></tr></thead><tbody><tr><td><code>prefer-ours</code></td><td>Ambiguous choices resolve to ours</td><td><code>high</code></td></tr><tr><td><code>prefer-theirs</code></td><td>Ambiguous choices resolve to theirs <strong>(default)</strong></td><td><code>high</code></td></tr><tr><td><code>prefer-merge</code></td><td>Resolve as much as possible</td><td><code>medium</code></td></tr><tr><td><code>prefer-safety</code></td><td>Only resolve very safe conflicts; skip whitespace and value-only</td><td><code>high</code></td></tr><tr><td><code>strict</code></td><td>Only <code>same_change</code>, <code>one_side_change</code>, and <code>delete_no_change</code></td><td><code>certain</code></td></tr></tbody></table><h3 id="policy-details" tabindex="-1">Policy Details <a class="header-anchor" href="#policy-details" aria-label="Permalink to &quot;Policy Details&quot;">​</a></h3><p><strong><code>prefer-ours</code></strong></p><ul><li>Whitespace conflicts: ours</li><li>Value-only conflicts: ours</li><li>Non-overlapping: allowed</li></ul><p><strong><code>prefer-theirs</code></strong> (default)</p><ul><li>Whitespace conflicts: theirs</li><li>Value-only conflicts: theirs</li><li>Non-overlapping: allowed</li></ul><p><strong><code>prefer-merge</code></strong></p><ul><li>Lower confidence threshold (<code>medium</code>)</li><li>All resolution types enabled</li><li>Most aggressive — resolves the most conflicts</li></ul><p><strong><code>prefer-safety</code></strong></p><ul><li>Disables whitespace-only and value-only resolution</li><li>Non-overlapping: allowed</li><li>Conservative — only resolves unambiguous conflicts</li></ul><p><strong><code>strict</code></strong></p><ul><li>Only the three safest conflict types</li><li>Requires <code>certain</code> confidence</li><li>Disables whitespace, value-only, and non-overlapping resolution</li></ul><h2 id="pattern-overrides" tabindex="-1">Pattern Overrides <a class="header-anchor" href="#pattern-overrides" aria-label="Permalink to &quot;Pattern Overrides&quot;">​</a></h2><p>Use glob patterns to apply different policies to specific files:</p><div class="language-json vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;policy&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;prefer-safety&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;patterns&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    &quot;*.lock&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;prefer-theirs&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    &quot;package.json&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;prefer-theirs&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    &quot;src/**/*.ts&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;prefer-ours&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    &quot;*.md&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;prefer-merge&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><h3 id="glob-syntax" tabindex="-1">Glob Syntax <a class="header-anchor" href="#glob-syntax" aria-label="Permalink to &quot;Glob Syntax&quot;">​</a></h3><table tabindex="0"><thead><tr><th>Pattern</th><th>Matches</th></tr></thead><tbody><tr><td><code>*</code></td><td>Any character except <code>/</code></td></tr><tr><td><code>**</code></td><td>Any character including <code>/</code></td></tr><tr><td><code>?</code></td><td>Exactly one character except <code>/</code></td></tr></tbody></table><ul><li>If a pattern has no <code>/</code>, it matches on the <strong>basename</strong> only (e.g., <code>*.lock</code> matches <code>path/to/yarn.lock</code>)</li><li>If a pattern contains <code>/</code>, it matches on the <strong>full path</strong> (e.g., <code>src/**/*.ts</code>)</li></ul><h3 id="priority" tabindex="-1">Priority <a class="header-anchor" href="#priority" aria-label="Permalink to &quot;Priority&quot;">​</a></h3><p>When multiple patterns match a file:</p><ol><li><strong>Most specific pattern</strong> (longest match) wins</li><li>Falls back to the global <code>policy</code></li><li>Falls back to <code>DEFAULT_POLICY</code> (<code>&quot;prefer-theirs&quot;</code>)</li></ol><h2 id="confidence-levels" tabindex="-1">Confidence Levels <a class="header-anchor" href="#confidence-levels" aria-label="Permalink to &quot;Confidence Levels&quot;">​</a></h2><p>The <code>minConfidence</code> setting (set implicitly by each policy) controls the minimum confidence score required for auto-resolution:</p><table tabindex="0"><thead><tr><th>Level</th><th>Score Threshold</th><th>Description</th></tr></thead><tbody><tr><td><code>certain</code></td><td>≥ 92</td><td>Only resolve when classification is near-certain</td></tr><tr><td><code>high</code></td><td>≥ 68</td><td>Resolve when classification is confident</td></tr><tr><td><code>medium</code></td><td>≥ 44</td><td>Resolve with moderate confidence</td></tr><tr><td><code>low</code></td><td>&lt; 44</td><td>Resolve even uncertain classifications</td></tr></tbody></table><h2 id="vs-code-extension-settings" tabindex="-1">VS Code Extension Settings <a class="header-anchor" href="#vs-code-extension-settings" aria-label="Permalink to &quot;VS Code Extension Settings&quot;">​</a></h2><p>When using the VS Code extension, you can also configure via VS Code settings:</p><table tabindex="0"><thead><tr><th>Setting</th><th>Default</th><th>Description</th></tr></thead><tbody><tr><td><code>gitwand.resolveWhitespace</code></td><td><code>true</code></td><td>Resolve whitespace-only conflicts</td></tr><tr><td><code>gitwand.minConfidence</code></td><td><code>&quot;high&quot;</code></td><td>Minimum confidence for auto-resolution</td></tr></tbody></table><p>These settings apply in addition to <code>.gitwandrc</code>. The more restrictive setting wins.</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("reference/config.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const config = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  config as default
};
